<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NuGetStagingDir Condition="'$(NuGetStagingDir)' == ''">$(MSBuildThisFileDirectory)../nuget-staging</NuGetStagingDir>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>CoreUtils.SkiaSharp.Static</PackageId>
        <Version>3.119.0</Version>
        <Authors>CoreUtils</Authors>
        <Description>SkiaSharp static library for Avalonia</Description>
        <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/andrewmd5/SkiaSharp.Static</PackageProjectUrl>
        <RepositoryUrl>https://github.com/andrewmd5/SkiaSharp.Static</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="buildTransitive/$(PackageId).targets" Pack="true" PackagePath="buildTransitive" />
    </ItemGroup>

    <!-- x64 libraries -->
    <ItemGroup>
        <None Include="$(NuGetStagingDir)/runtimes/win-x64/native/skia.lib" Pack="true" PackagePath="runtimes/win-x64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-x64/native/skia.pdb" Pack="true" PackagePath="runtimes/win-x64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-x64/native/SkiaSharp.lib" Pack="true" PackagePath="runtimes/win-x64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-x64/native/SkiaSharp.pdb" Pack="true" PackagePath="runtimes/win-x64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-x64/native/libHarfBuzzSharp.lib" Pack="true" PackagePath="runtimes/win-x64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-x64/native/libHarfBuzzSharp.pdb" Pack="true" PackagePath="runtimes/win-x64/native/" />
    </ItemGroup>

    <!-- arm64 libraries -->
    <ItemGroup>
        <None Include="$(NuGetStagingDir)/runtimes/win-arm64/native/skia.lib" Pack="true" PackagePath="runtimes/win-arm64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-arm64/native/skia.pdb" Pack="true" PackagePath="runtimes/win-arm64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-arm64/native/SkiaSharp.lib" Pack="true" PackagePath="runtimes/win-arm64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-arm64/native/SkiaSharp.pdb" Pack="true" PackagePath="runtimes/win-arm64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-arm64/native/libHarfBuzzSharp.lib" Pack="true" PackagePath="runtimes/win-arm64/native/" />
        <None Include="$(NuGetStagingDir)/runtimes/win-arm64/native/libHarfBuzzSharp.pdb" Pack="true" PackagePath="runtimes/win-arm64/native/" />
    </ItemGroup>
</Project>
