<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows7.0</TargetFramework>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <BuildDir>$(MSBuildThisFileDirectory)../out/windows/x64</BuildDir>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>CoreUtils.SkiaSharp.Static</PackageId>
        <Version>3.119.0</Version>
        <Authors>CoreUtils</Authors>
        <Description>SkiaSharp static library for Avalonia</Description>
        <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/andrewmd5/SkiaSharp.Static</PackageProjectUrl>
        <RepositoryUrl>https://github.com/andrewmd5/SkiaSharp.Static</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="buildTransitive/$(PackageId).targets" Pack="true" PackagePath="buildTransitive" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(BuildDir)/libHarfBuzzSharp.lib"
            Pack="true"
            PackagePath="runtimes/win-$(TargetArch)/native/">
            <Link>libHarfBuzzSharp.lib</Link>
        </None>
        <None Include="$(BuildDir)/libHarfBuzzSharp.pdb"
            Pack="true"
            PackagePath="runtimes/win-$(TargetArch)/native/">
        </None>
        <None Include="$(BuildDir)/skia.lib"
            Pack="true"
            PackagePath="runtimes/win-$(TargetArch)/native/">
            <Link>skia.lib</Link>
        </None>
        <None Include="$(BuildDir)/SkiaSharp.lib"
            Pack="true"
            PackagePath="runtimes/win-$(TargetArch)/native/">
            <Link>SkiaSharp.lib</Link>
        </None>
    </ItemGroup>
</Project>