name: build-skia-2.88.9
on:
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "args.gn"
defaults:
  run:
    shell: nu {0}

env:
  SkiaSharpVersion: 2.88.9
jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write
      attestations: write
      contents: write
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          arch: ${{ matrix.arch }}
      - name: Install LLVM 21
        run: winget install --id LLVM.LLVM --accept-package-agreements --accept-source-agreements --disable-interactivity
      - uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
      - uses: ./.github/actions/deploy
